library("rstan")
library("psych")

options(scipen = 999)
options(max.print = 100000)
rstan_options(auto_write = TRUE)
options(mc.cores = parallel::detectCores())

source("modules/extractSamples.R")
source("modules/hdi.R")
source("modules/summarizeSamples.R")
source("modules/zeros.R")
source("modules/generateData.R")
source("modules/swapColumns.R")
source("modules/euclideanDistance.R")
source("modules/reorientLoadings.R")
source("modules/efa.R")
source("modules/befa.R")
source("modules/testData.R")
